### ISSUE TITLE
Widget wont play embedded podcast

### ISSUE THREAD

**Issue by Englund1** [ycfreeman/jplayer-podcast-wordpress-widget#1]
Hi Freeman, I downloaded your widget/plugin jPlayer, the player looks great,
but we added the RSS feed from iTunes and it wont play the embedded podcast, can you help me?

The website we are using your plugin on is:
http://thefedmanwalking.com/

the feed we put in was:
https://itunes.apple.com/us/podcast/marketing-differently/id1089794833

we are hosting the audio on spreaker.com:
www.speaker.com/show/1651436/episodes/feed

**Comment by ycfreeman** [comment]
it doesn't look like there's any mp3 in your feed

i've traced your itunes link and got another link to a different feed
http://www.spreaker.com/show/1651417/episodes/feed
and that seems to work

try to check your feed and look for lines like 

```
<enclosure url="http://api.spreaker.com/download/episode/7803060/cmp_test_audio.mp3" length="0" type="audio/mpeg"/>
```

this is how the widget look for playable files

let me know if it solves your issue

**Comment by ycfreeman** [comment]
@Englund1 ^
